= Pax Exam User Manual 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: Pax Exam 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== In-Container Testing for OSGi, Java EE and CDI

== OSGi Testing

* Pax Exam lets you take control of the OSGi framework, the test framework (e.g. JUnit) and your system under test at the same time.
* Pax Exam is also able to bootstrap a Apache Karaf container allowing you to directly execute commands, deploy features, etc.
* Pax Exam has a test driver and a test container. The driver launches the OSGi framework and the system under test. It builds on-the-fly bundles from your test cases and injects them into the container. The driver is a plain old Java application and does not itself require an OSGi framework.
* The test container comes in two flavours: The Native Container launches an embedded OSGi framework in the test driver VM. With the Forked Container, the system under test runs in a separate Java virtual machine under remote control from the test driver.
* Test containers support different strategies for restarting or reusing the running OSGi framework for each test.
* With the PaxExam JUnit runner, you simply need to add some special annotations and a configuration method to a JUnit class to run your OSGi tests. Thanks to this runner, any JUnit integration (e.g. in Eclipse or Maven Surefire) works with Pax Exam out of the box.
* Pax Exam itself is distributed as Maven artifacts and lets you provision Maven bundles to your OSGi framework directly from local or remote Maven repositories.
* Pax Exam supports all major OSGi frameworks (Equinox, Felix, Knopflerfish), based on OSGi 4.3 or higher.
* Read more: Getting Started with OSGi Tests

== Java EE 7 and CDI 1.1 Testing

* Pax Exam 4.x generalizes the in-container testing approach to cover not only OSGi, but also Java EE and CDI components and applications.
* Simply add `@RunWith(PaxExam.class)` to your JUnit test classes and let Pax Exam launch a full-blown Java EE server or a stand-alone CDI container and execute your tests within the container.
* In Java EE mode, Pax Exam uses sensible defaults to build a test WAR on the fly, based on the classpath. There is no need to explicitly configure this WAR for each test.
* All classes of a test suite can share the same setup.
* Pax Exam 4.x supports GlassFish 4.x and Wildfly 8.x.
* In CDI Java SE mode, Pax Exam supports Weld 2.x.
* For other Java EE 6 or CDI 1.0 containers, have a look at Pax Exam 3.x.
* Read more: Getting Started with Java EE Tests and Getting Started with CDI Tests

== Unit Test Frameworks

Pax Exam is best used with JUnit 4, but also supports TestNG 6.

== What's New?


= Getting Started

== Getting Started with OSGi Tests
== Getting Started with Java EE Tests
== Getting Started with CDI Tests

== Maven Dependencies

= Concepts

== Operation Mode

Pax Exam 3.x supports four operation modes OSGi, Java EE, CDI and Web. OSGi is the default mode and the only one available in Pax Exam 2.x.

=== OSGi Mode

In OSGi mode, Pax Exam starts a test container with an OSGi framework, lets you provision bundles by configuration options and builds a probe bundle from the test classes and resources of your current project.

=== Java EE Mode

In Java EE mode, Pax Exam starts a Java EE application server, deploys WAR modules defined in configuration options and builds a WAR probe from the contents of the current class path. The WAR probe includes your test cases which are invoked by the driver via a servlet bridge. The tests are executed within the Java EE container, the test results are returned to the driver as a HTTP result.

=== CDI Mode

In CDI mode, Pax Exam starts a CDI container in the current VM, providing the subset of CDI functionality which does not require a Java EE environment. CDI mode does not use probes, all tests are directly invoked by the driver after injecting dependencies using the CDI bean manager.
=== Web Mode

In Web mode, Pax Exam starts a servlet container in the current VM. This mode supports web-only containers like Tomcat or Jetty, using either CDI or Spring for dependency injection.

=== Framework

In the context of Pax Exam (OSGi mode), the term framework usually refers to the OSGi framework running the system under test.

=== System under test

The system under test is the collection of your application and library bundles.

Pax Exam aims at executing black box tests, but in fact the box (i.e. the container) is slightly grey, as Pax Exam adds some bundles of its own and the probe.

=== Test Container

The test container is a thin wrapper around the framework, the system under test and the probe\, adding the ability to communicate with the driver and the outside world in general.

=== Reactor

The reactor manages the collection of all tests to be executed in one or more different containers. The reactor starts and stops the required containers and provisions bundles and probes to the containers.

=== Driver

The driver is the entry point into Pax Exam. It evaluates configuration options and creates a reactor based on these options. The driver receives the test results and handles them in an implementation dependent way.

Pax Exam includes different drivers:

* The JUnit 4 driver integrates Pax Exam with JUnit 4.12.
* The JUnit 5 driver integrates Pax Exam with JUnit 5, also known as JUnit Jupiter.
* The TestNG driver integrates Pax Exam with TestNG.

=== Probe

The probe is a synthetic artifact which Pax Exam adds to the system under test.

In OSGi mode, Pax Exam creates the probe on the fly with the help of Tinybundles. The probe contains the current test class and all classes and resources found under the same root.

In Java EE or Web mode, the probe is a WAR containing all test classes, resources and dependencies on the classpath, the servlet bridge and some other Pax Exam dependencies.

In CDI mode, there is no probe, all test methods are invoked directly.

=== Configuration

The configuration determines the set of bundles or modules provisioned to the container, and some system and environment properties.

There are different methods of specifying configuration options. In OSGi mode, you typically use a annotated by `@Configuration` with return type `Option[]`.

In the other modes, the test container is automatically configured from the contents of the class path.

If you need to customize the contents of the WAR probe in Java EE or Web mode, you can override the defaults in a `@Configuration` method.


= Test Containers
== OSGi Containers
== Java EE Containers
== CDI Containers
== Web Containers
== Karaf Container

= Reactor Strategies

= Drivers
== JUnit 4 Driver
== JUnit 5 Driver
== TestNG Driver
    
= Dependency Injection
= Server Mode
= Exam Maven Plugin
= Configuration
== Configuration Options
== Logging Configuration
=  Diagnosis
=  FAQ




// Return to normal title levels 
:leveloffset: 0
